### ISSUE TITLE
Logo For Librery App

### ISSUE THREAD

**Issue by zularizal** [harisont/Librery#51]
Hi @harisont , I'm a graphics designer, after I review your project I want to contribute by creating a new logo and icon for your project and you do not have to pay for this because it's free. What do you think?

**Comment by harisont** [comment]
Hi! Yeah, thank you, that'd be great, the current icon is quite bad (I just rearranged one of the LibreOffice logos to make italian people understand the word game).
So yeah, feel free :)

**Comment by zularizal** [comment]
Hi, I've designed some logos, what do you think? Which one do you like? if there is something you want to change please let me know

![logo](https://user-images.githubusercontent.com/38547278/42062614-4b809590-7b58-11e8-8f83-5def07cf0ca3.png)

**Comment by zularizal** [comment]
What do you think with this, which one do you like A, b or c?
And I have also included an example icon on the logo.

![rect4619](https://user-images.githubusercontent.com/38547278/42064793-eb407d80-7b61-11e8-8cab-84c668594d75.png)

**Comment by harisont** [comment]
I think A is lovely, and I prefer the logo on the right side, even though they're both really cool.

**Comment by harisont** [comment]
Also, if you don' mind, I think it would be cool to crop the red book (c) and use it in the app as a replacement for missing thumbnails in situations like this (my current thumbnail replacement is awful haha):
![repl](https://user-images.githubusercontent.com/17993183/42065378-de1eb35a-7b3a-11e8-9e92-2b95f4dd1289.jpg)

**Comment by zularizal** [comment]
Do you mean like this?

If nothing else wants to change, I will upload this logo to the drive and send you a pull request

![rect4911](https://user-images.githubusercontent.com/38547278/42065642-4cd389c6-7b66-11e8-84f8-1e7c4313b5f5.png)

**Comment by zularizal** [comment]
Hi, I already uploaded the logo to drive, check this link

https://drive.google.com/open?id=1PQSSbGGopETlKxvdoxlbIGlq3ssuOICc

And also I have sent a pull request #54

**Comment by harisont** [comment]
Okay, I merged it. There will be a new 2.1 release with several GUI improvements and I'll be happy to use the new icon and mention you in the release notes.
Thanks again! I really appreciate your work.

**Comment by zularizal** [comment]
It was my pleasure
